name: Linting

on:
  pull_request:
    branches: [main]

jobs:
  terraform-fmt:
    name: Terraform Format Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      
      - name: Terraform Format Check
        run: terraform fmt -check -recursive terraform/
  
  markdown-lint:
    name: Markdown Linting
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Lint Markdown files
        uses: articulate/actions-markdownlint@v1
        with:
          files: '**/*.md'
          ignore: node_modules
